ingress:
  host: buildmystudy.com
  pathType: Prefix

service:
  port: 80

spring:
  image:
    repository: 440744253928.dkr.ecr.ap-northeast-2.amazonaws.com/chathub/backend   # ECR에 저장된 스프링 이미지 URL
    tag: latest
  service:
    port: 80
  containerPort: 8080
  datasource:
    url: jdbc:mysql://database-1.c9s06ug8a482.ap-northeast-2.rds.amazonaws.com:3306/mydb
    username: yourusername
    password: yourpassword
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "your-client-id"
            client-secret: "your-client-secret"

front:
  image:
    repository: 440744253928.dkr.ecr.ap-northeast-2.amazonaws.com/chathub/front
    tag: latest
  service:
    port: 80
  containerPort: 3000
  env:
    NEXT_PUBLIC_API_BASE_URL: "https://buildmystudy.com"
