ingress:
  host: buildmystudy.com
  pathType: Prefix

spring:
  image:
    repository: 440744253928.dkr.ecr.ap-northeast-2.amazonaws.com/chathub/backend   # ECR에 저장된 스프링 이미지 URL
    tag: latest
  service:
    port: 80
  containerPort: 8080
  datasource:
    url: jdbc:mysql://<RDS_ENDPOINT>:3306/mydb
    username: yourusername
    password: yourpassword

front:
  image:
    repository: 440744253928.dkr.ecr.ap-northeast-2.amazonaws.com/chathub/front
    tag: latest
  service:
    port: 80
  containerPort: 3000
  env:
    NEXT_PUBLIC_API_BASE_URL: "https://buildmystudy.com"
