services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-hub
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: worldcup7!
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: worldcup7!
      MYSQL_DATABASE: mydb
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
