apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: "{{ .Values.front.labels }}"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "{{ .Values.front.labels }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.front.labels }}"
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: "{{ .Values.front.labels }}"
          image: "{{ .Values.front.image.repository }}:{{ .Values.front.image.tag }}"
          ports:
            - containerPort: {{ .Values.front.containerPort }}
          resources:
            requests:
              memory: "100Mi"
              cpu: "150m"
            limits:
              memory: "200Mi"
              cpu: "300m"
