apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: "{{ .Values.front.image.repository }}:{{ .Values.front.image.tag }}"
          ports:
            - containerPort: {{ .Values.front.containerPort }}
          resources:
            requests:
              memory: "100Mi"
              cpu: "150m"
            limits:
              memory: "200Mi"
              cpu: "300m"
