apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buildmystudy-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: spring-service
                port:
                  number: {{ .Values.spring.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-service
                port:
                  number: {{ .Values.front.service.port }}
