apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buildmystudy-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: spring-service
                port:
                  number: {{ .Values.spring.service.port }}
          - path: /
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: front-service
                port:
                  number: {{ .Values.front.service.port }}
