apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: "{{ .Values.spring.image.repository }}:{{ .Values.spring.image.tag }}"
          ports:
            - containerPort: {{ .Values.spring.containerPort }}
          resources:
            requests:
              memory: "250Mi"
              cpu: "400m"
            limits:
              memory: "500Mi"
              cpu: "800m"
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/application.yml"
            - name: DB_URL
              value: "{{ .Values.spring.datasource.url }}"
            - name: DB_USERNAME
              value: "{{ .Values.spring.datasource.username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.spring.datasource.password }}"
            - name: GITHUB_CLIENT_ID
              value: "{{ index .Values.spring.security.oauth2.client.registration.github "client-id" }}"
            - name: GITHUB_CLIENT_SECRET
              value: "{{ index .Values.spring.security.oauth2.client.registration.github "client-secret" }}"

          volumeMounts:
            - name: spring-config
              mountPath: /config/application.yml
              subPath: application.yml

          livenessProbe:
            httpGet:
              path: /api/health
              port: { { .Values.spring.containerPort } }
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
            successThreshold: 1

            readinessProbe:
              httpGet:
                path: /api/health
                port: { { .Values.spring.containerPort } }
              initialDelaySeconds: 5
              periodSeconds: 10
              failureThreshold: 3
              successThreshold: 1

      volumes:
        - name: spring-config
          configMap:
            name: spring-config
