apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.spring.labels }}-deployment"
  labels:
    app: "{{ .Values.spring.labels }}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "{{ .Values.spring.labels }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.spring.labels }}"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: "{{ .Values.spring.labels }}"
          image: "{{ .Values.spring.image.repository }}:{{ .Values.spring.image.tag }}"
          ports:
            - containerPort: {{ .Values.spring.containerPort }}
          resources:
            requests:
              memory: "250Mi"
              cpu: "400m"
            limits:
              memory: "500Mi"
              cpu: "800m"
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/config/application.yml"
            - name: DB_URL
              value: "{{ .Values.spring.datasource.url }}"
            - name: DB_USERNAME
              value: "{{ .Values.spring.datasource.username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.spring.datasource.password }}"
            - name: GITHUB_CLIENT_ID
              value: "{{ index .Values.spring.security.oauth2.client.registration.github "client-id" }}"
            - name: GITHUB_CLIENT_SECRET
              value: "{{ index .Values.spring.security.oauth2.client.registration.github "client-secret" }}"

          volumeMounts:
            - name: spring-config
              mountPath: /config/application.yml
              subPath: application.yml

          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.spring.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.spring.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1

      volumes:
        - name: spring-config
          configMap:
            name: spring-config
