apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: {{ .Values.spring.service.port }}
      targetPort: {{ .Values.spring.containerPort }}
